# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izsek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsebina', models.TextField(blank=True, null=True)),
                ('zacetek', models.TimeField(blank=True, null=True)),
                ('konec', models.TimeField(blank=True, null=True)),
                ('red', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oddaja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ime', models.TextField(blank=True, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posnetek',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('naslov', models.TextField(blank=True, null=True)),
                ('povezava_4d', models.URLField(blank=True, null=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('datum', models.DateField(blank=True, null=True)),
                ('dolzina', models.TimeField(blank=True, null=True)),
                ('oddaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Oddaja')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ime', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='oddaja',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Program'),
        ),
        migrations.AddField(
            model_name='oddaja',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Tip'),
        ),
        migrations.AddField(
            model_name='izsek',
            name='posnetek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Posnetek'),
        ),
    ]
