# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kamnolom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izsek',
            name='posnetek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Posnetek'),
        ),
        migrations.AlterField(
            model_name='oddaja',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Program'),
        ),
        migrations.AlterField(
            model_name='oddaja',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Tip'),
        ),
        migrations.AlterField(
            model_name='posnetek',
            name='oddaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kamnolom.Oddaja'),
        ),
    ]
