# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamnolom', '0002_auto_20170330_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izsek',
            name='red',
        ),
        migrations.AddField(
            model_name='oddaja',
            name='povezava',
            field=models.URLField(blank=True, null=True),
        ),
    ]
