# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamnolom', '0003_auto_20170331_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddaja',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
