# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamnolom', '0004_oddaja_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddaja',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='oddaja'),
        ),
    ]
