# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    #0006_auto_20170331_2256
    dependencies = [
        ('kamnolom', '0006_auto_20170331_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izsek',
            name='vsebina',
            field=models.TextField(null=True),
        ),
    ]
