# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamnolom', '0009_auto_20170402_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='posnetek',
            name='podnapisi',
            field=models.FileField(blank=True, null=True, upload_to='podnapisi'),
        ),
    ]
